Repository zendframework/zend-mvc, pull requests merged in 2019-02, with the labels that each got.

#301 Bump minimum php to 7.2 for next major
  .gitignore
  .travis.yml
  CHANGELOG.md
  composer.json
  composer.lock
  test/Application/ControllerIsDispatchedTest.php
  test/Application/ExceptionsRaisedInDispatchableShouldRaiseDispatchErrorEventTest.php
  test/Application/InabilityToRetrieveControllerShouldTriggerDispatchErrorTest.php
  test/Application/InabilityToRetrieveControllerShouldTriggerExceptionTest.php
  test/Application/InitializationIntegrationTest.php
  test/Application/InvalidControllerTypeShouldTriggerDispatchErrorTest.php
  test/ApplicationTest.php
  test/Controller/AbstractControllerTest.php
  test/Controller/ActionControllerTest.php
  test/Controller/ControllerManagerTest.php
  test/Controller/IntegrationTest.php
  test/Controller/LazyControllerAbstractFactoryTest.php
  test/Controller/MiddlewareControllerTest.php
  test/Controller/Plugin/AcceptableViewModelSelectorTest.php
  test/Controller/Plugin/ForwardTest.php
  test/Controller/Plugin/LayoutTest.php
  test/Controller/Plugin/ParamsTest.php
  test/Controller/Plugin/RedirectTest.php
  test/Controller/Plugin/UrlTest.php
  test/Controller/RestfulControllerTest.php
  test/HttpMethodListenerTest.php
  test/ModuleRouteListenerTest.php
  test/ResponseSender/AbstractResponseSenderTest.php
  test/Service/ControllerManagerFactoryTest.php
  test/Service/HttpMethodListenerFactoryTest.php
  test/Service/ServiceListenerFactoryTest.php
  test/Service/ServiceManagerConfigTest.php
  test/Service/ViewHelperManagerFactoryTest.php
  test/View/CreateViewModelListenerTest.php
  test/View/DefaultRendereringStrategyTest.php
  test/View/ExceptionStrategyTest.php
  test/View/InjectTemplateListenerTest.php
  test/View/InjectViewModelListenerTest.php
  test/View/RouteNotFoundStrategyTest.php
  test/_autoload.php
Labels: enhancement

#305 Adds missing language strings to unreadable code examples
  docs/book/intro.md
Labels: bug, documentation

#307 Fixes wrong headline in migration guide
  docs/book/migration/to-v2-7.md
Labels: bug, documentation

#277 remove commented code at ServiceManagerConfig::configureServiceManager()
  src/Service/ServiceManagerConfig.php
Labels: bug

#288 reduce repetitive spl_object_hash() at SendResponseEvent
  src/ResponseSender/SendResponseEvent.php
Labels: enhancement

#309 Adds missing file for workaround in navigation and homepage
  docs/book/index.md
Labels: bug, documentation
